server:
  port: 8181
  servlet:
    context-path: /shop-carts


#integration:
#  urlCore: "http://localhost:8189/shop/api/v1/products"

integrations:
  product-service:
    url: http://localhost:8189/shop-core/
    connect-timeout: 5000
    read-timeout: 10000
    write-timeout: 5000


cart-service:
  cart-prefix: gb_shop_cart_


#spring:
#  redis:
#    port: 6379
#    host: localhost
